
version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run dashboard/app.py --server.port=8501 --server.address=0.0.0.0
