
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-recommender
  template:
    metadata:
      labels:
        app: stock-recommender
    spec:
      containers:
      - name: stock-recommender
        image: stock-recommender:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: stock-recommender-service
spec:
  selector:
    app: stock-recommender
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer
